### ISSUE TITLE
Cannot write metadata to root object

### ISSUE THREAD

**Issue by drewcassidy** [devlooped/json#85]
## Describe the Bug

I have the following call. The input items are batched so "VersionFIle" at this point is a single item. it does have the "a" metadata variable
```xml
    <JsonPoke Content="{}" Query="$" Value="@(VersionFile)" Properties="a">
      <Output TaskParameter="Content" PropertyName="_JSON"/>
    </JsonPoke>
```

## Expected Behavior

Output json would be 

```json
{
  "a": "Value of a"
}
```
## Exception with Stack Trace

```text
0>/Users/drewcassidy/Code/Shabby/KSPBuildTools/KSPCommon.targets(89,5): Error MSB4018 : The "JsonPoke" task failed unexpectedly.
System.InvalidOperationException: The parent is missing.
   at Newtonsoft.Json.Linq.JToken.Replace(JToken value)
   at JsonPoke.Execute() in /_/src/JsonPoke/JsonPoke.cs:line 207
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

## Version Info

JsonPoke 1.2.0

## Additional Info

using a different query like "$.thing" does succeed

**Comment by drewcassidy** [comment]
lack of responses does not mean this bug does not exist

**Comment by drewcassidy** [comment]
still exists

**Comment by drewcassidy** [comment]
No
